name: A workflow demo
on: [push, pull_request]
jobs:
  my_first_job:
    name: Hello world action
    runs-on: windows-latest
    steps:
      - name: Print a hello
      - uses: actions/checkout@v1
      - uses: ./action-a
        with:
          MY_NAME: "Yingtong"
  my_second_job:
    name: Bye-bye world action
    runs-on: windows-latest
    needs: my_first_job
    steps:
      - name: Print a bye-bye
      - uses: actions/checkout@v1
      - uses: ./action-a
        with:
          MY_NAME: "Yingtong"
