name: A workflow for my Hello World file
on: [push, pull_request]
jobs:
  my_first_job:
    name: Hello world action
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: ./action-a
        with:
          MY_NAME: "Mona"
